config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#homepage'

  resources :categories
  resources :ingredients
  resources :dishes
  resources :restaurants do
    collection do
      get 'homepage'
      post 'homepage'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name, :address, :phone

  has_many :dishes
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  def homepage
    @restaurants = Restaurant.all.order("name")
    @restaurants = Restaurant.joins(:dishes).where(dishes: {category_id: params[:category_id]}).order("name").uniq unless params[:category_id].blank?
    @restaurants = Restaurant.joins(:dishes).where("UPPER(dishes.name) like ?" , "%#{params[:search_term].to_s.upcase}%").uniq unless params[:search_term].blank?
  end
  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :phone, :address)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def postTime_to_prepare(time_to_prepare)
    time_to_prepare.strftime("%H:%M")
  end
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :restaurant_phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :restaurant_address %>
  </div>

  <button type="submit" class="btn btn-default" aria-label="Left Align">
    <span class="glyphicon glyphicon-plus " aria-hidden="true"></span>
    Create
  </button>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/homepage.html.erb
<div class="row">
  <div class="col-xs-8">
    <% @restaurants.each do |restaurant| %>
      <h2><%= link_to restaurant.name, restaurant %></h2>
      <hr>
    <% end %>
  </div>
  <div class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Categories</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% Category.all.each do |category| %>
            <li>
              <%= link_to category.description, homepage_restaurants_path(category_id: category.id) %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Search</h3>
      </div>
      <div class="panel-body">
          <%= form_tag("/restaurants/homepage", method: "post") do %>
          <%= text_field_tag(:search_term) %>
          <%= submit_tag("Buscar") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.address %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurant.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<br>

<h3><b>Pratos</b></h3>

<div class="pratos">
  <% @restaurant.dishes.order(:name).each do |dish| %>
    <hr>
    <h4><b><%= dish.category.description %></b></h4>
    <h4><%= dish.name %></h4>
    <h4> Ingredients:
      <% dish.ingredients.each do |ingredient| %>
        <%= ingredient.description + "."%>
      <% end %>
    </h4>
    <h4>Price: R$<%= dish.price %>0</h4>
    <h4>Time to prepare: <%= postTime_to_prepare dish.time_to_prepare %></h4>
  <% end %>
  <hr>
</div>